name: Deploy Autom치tico (GHCR)

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aprendendolinux/mail-report

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Baixar c칩digo
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extrair metadados (Tags Docker)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=dev-latest,enable=${{ github.ref == 'refs/heads/dev' }}
            type=ref,event=tag
            type=sha,format=short
      - name: Definir Vers칚o (Tag ou Hash)
        id: prep
        run: |
          # Pega os 7 primeiros d칤gitos do Hash do commit
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # CEN츼RIO 1: 칄 uma TAG (Produ칞칚o) -> Usa o nome limpo (ex: v1.0.6)
            VERSION=${GITHUB_REF#refs/tags/}
            echo "Modo: TAG DE PRODU칂츾O"
            
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            # CEN츼RIO 2: 칄 a DEV -> Usa 'dev-' + Hash (ex: dev-a1b2c3d)
            VERSION="dev-${SHORT_SHA}"
            echo "Modo: DESENVOLVIMENTO (HASH)"
            
          else
            # CEN츼RIO 3: Main sem tag (Fallback) -> Usa 'latest-' + Hash
            VERSION="latest-${SHORT_SHA}"
            echo "Modo: MAIN (LATEST)"
          fi
          
          echo "Vers칚o Calculada: $VERSION"
          # Salva na vari치vel de sa칤da para o pr칩ximo passo usar
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build e Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # --- INJETA A VERS츾O NO DOCKERFILE ---
          build-args: |
            APP_VERSION=${{ steps.prep.outputs.VERSION }}

      - name: Atualizar Portainer (Produ칞칚o)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "游 Nova Tag Detectada: Disparando webhook de Produ칞칚o..."
          curl -k -X POST "${{ secrets.PORTAINER_WEBHOOK_PROD }}"
          
      # - name: Atualizar Portainer (Dev)
      #   if: github.ref == 'refs/heads/dev'
      #   run: |
      #     echo "游빍 Branch Dev: Disparando webhook de Desenvolvimento..."
      #     curl -k -X POST "${{ secrets.PORTAINER_WEBHOOK_DEV }}"